@echo off
echo Starting Backend...
start cmd /k ".\venv\Scripts\python.exe -m uvicorn app.main:app --port 8080"
echo Starting Frontend...
start cmd /k ".\venv\Scripts\python.exe -m streamlit run frontend\streamlit_app.py"
